/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Controlador.*;

/**
 *
 * @author alexb
 */
public class Ventana_2_vuelo extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_2_vuelo
     */
    public Ventana_2_vuelo() {
        initComponents();
        formato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caja_numero_ventana2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combox_origen_ventana2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combox_destino_ventana2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combox_Salida_ventana2 = new javax.swing.JComboBox<>();
        combox_Llegada_ventana2 = new javax.swing.JComboBox<>();
        boton_agregar_ventana2 = new javax.swing.JButton();
        boton_actualizar_ventana2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combox_Escala_ventana2 = new javax.swing.JComboBox<>();
        comboEscala_llegada_ventana2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Escalas = new javax.swing.JTable();
        combox_Salida_Escala_ventana2 = new javax.swing.JComboBox<>();
        boton_agregar_Escala = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabala_vuelos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero");

        jLabel2.setText("Origen");

        combox_origen_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        combox_origen_ventana2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combox_origen_ventana2MouseClicked(evt);
            }
        });

        jLabel3.setText("Destino");

        combox_destino_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel4.setText("Salida");

        jLabel5.setText("Llegada");

        combox_Salida_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combox_Llegada_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        boton_agregar_ventana2.setText("Agregar");

        boton_actualizar_ventana2.setText("Actualizar");

        jLabel6.setText("Escalas");

        jLabel7.setText("Llegada");

        jLabel8.setText("Salida");

        combox_Escala_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboEscala_llegada_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Tabla_Escalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Escalas);

        combox_Salida_Escala_ventana2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        boton_agregar_Escala.setText("+");
        boton_agregar_Escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_EscalaActionPerformed(evt);
            }
        });

        Tabala_vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabala_vuelos);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("VUELOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combox_destino_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combox_Llegada_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caja_numero_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combox_origen_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(combox_Salida_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton_agregar_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(boton_actualizar_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combox_Escala_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboEscala_llegada_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combox_Salida_Escala_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_agregar_Escala, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caja_numero_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(combox_origen_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(combox_Salida_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combox_destino_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(combox_Llegada_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_agregar_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_actualizar_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combox_Escala_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEscala_llegada_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combox_Salida_Escala_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_agregar_Escala)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_agregar_EscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_EscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_agregar_EscalaActionPerformed

    private void combox_origen_ventana2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combox_origen_ventana2MouseClicked
       
    }//GEN-LAST:event_combox_origen_ventana2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_2_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_2_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_2_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_2_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_2_vuelo().setVisible(true);
            }
        });
    }

    public JTable getTabala_vuelos() {
        return Tabala_vuelos;
    }

    public void setTabala_vuelos(JTable Tabala_vuelos) {
        this.Tabala_vuelos = Tabala_vuelos;
    }

    public JTable getTabla_Escalas() {
        return Tabla_Escalas;
    }

    public void setTabla_Escalas(JTable Tabla_Escalas) {
        this.Tabla_Escalas = Tabla_Escalas;
    }

    public JButton getBoton_actualizar_ventana2() {
        return boton_actualizar_ventana2;
    }

    public void setBoton_actualizar_ventana2(JButton boton_actualizar_ventana2) {
        this.boton_actualizar_ventana2 = boton_actualizar_ventana2;
    }

    public JButton getBoton_agregar_Escala() {
        return boton_agregar_Escala;
    }

    public void setBoton_agregar_Escala(JButton boton_agregar_Escala) {
        this.boton_agregar_Escala = boton_agregar_Escala;
    }

    public JButton getBoton_agregar_ventana2() {
        return boton_agregar_ventana2;
    }

    public void setBoton_agregar_ventana2(JButton boton_agregar_ventana2) {
        this.boton_agregar_ventana2 = boton_agregar_ventana2;
    }

    public JTextField getCaja_numero_ventana2() {
        return caja_numero_ventana2;
    }

    public void setCaja_numero_ventana2(JTextField caja_numero_ventana2) {
        this.caja_numero_ventana2 = caja_numero_ventana2;
    }

    public JComboBox<String> getComboEscala_llegada_ventana2() {
        return comboEscala_llegada_ventana2;
    }

    public void setComboEscala_llegada_ventana2(JComboBox<String> comboEscala_llegada_ventana2) {
        this.comboEscala_llegada_ventana2 = comboEscala_llegada_ventana2;
    }

    public JComboBox<String> getCombox_Escala_ventana2() {
        return combox_Escala_ventana2;
    }

    public void setCombox_Escala_ventana2(JComboBox<String> combox_Escala_ventana2) {
        this.combox_Escala_ventana2 = combox_Escala_ventana2;
    }

    public JComboBox<String> getCombox_Llegada_ventana2() {
        return combox_Llegada_ventana2;
    }

    public void setCombox_Llegada_ventana2(JComboBox<String> combox_Llegada_ventana2) {
        this.combox_Llegada_ventana2 = combox_Llegada_ventana2;
    }

    public JComboBox<String> getCombox_Salida_Escala_ventana2() {
        return combox_Salida_Escala_ventana2;
    }

    public void setCombox_Salida_Escala_ventana2(JComboBox<String> combox_Salida_Escala_ventana2) {
        this.combox_Salida_Escala_ventana2 = combox_Salida_Escala_ventana2;
    }

    public JComboBox<String> getCombox_Salida_ventana2() {
        return combox_Salida_ventana2;
    }

    public void setCombox_Salida_ventana2(JComboBox<String> combox_Salida_ventana2) {
        this.combox_Salida_ventana2 = combox_Salida_ventana2;
    }

    public JComboBox<String> getCombox_destino_ventana2() {
        return combox_destino_ventana2;
    }

    public void setCombox_destino_ventana2(JComboBox<String> combox_destino_ventana2) {
        this.combox_destino_ventana2 = combox_destino_ventana2;
    }

    public JComboBox<String> getCombox_origen_ventana2() {
        return combox_origen_ventana2;
    }

    public void setCombox_origen_ventana2(JComboBox<String> combox_origen_ventana2) {
        this.combox_origen_ventana2 = combox_origen_ventana2;
    }

    
    DefaultTableModel modelito2=new DefaultTableModel();
     DefaultTableModel modelito3=new DefaultTableModel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabala_vuelos;
    private javax.swing.JTable Tabla_Escalas;
    private javax.swing.JButton boton_actualizar_ventana2;
    private javax.swing.JButton boton_agregar_Escala;
    private javax.swing.JButton boton_agregar_ventana2;
    private javax.swing.JTextField caja_numero_ventana2;
    private javax.swing.JComboBox<String> comboEscala_llegada_ventana2;
    private javax.swing.JComboBox<String> combox_Escala_ventana2;
    private javax.swing.JComboBox<String> combox_Llegada_ventana2;
    private javax.swing.JComboBox<String> combox_Salida_Escala_ventana2;
    private javax.swing.JComboBox<String> combox_Salida_ventana2;
    private javax.swing.JComboBox<String> combox_destino_ventana2;
    private javax.swing.JComboBox<String> combox_origen_ventana2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

 
    private void formato() {
        
    String []s={"Ciudad","llegada","Salida","Escala"};
     modelito2.setColumnIdentifiers(s);
     Tabla_Escalas.setModel(modelito2);
    
    String []st={"Numero","Descripcion","Salida","Llegada","Duracion"};
    modelito3.setColumnIdentifiers(st);
     Tabala_vuelos.setModel(modelito3);
    }
}
